import React, {useMemo, useState} from 'react'
import {createRoot} from 'react-dom/client'
import {Bell, ChevronDown, ChevronLeft, ChevronRight, Clapperboard, CloudUpload, Command, FileVideo, HelpCircle, Home, ImagePlus, LayoutDashboard, Menu, MessageSquare, MoreVertical, PlaySquare, Plus, Search, Settings, ShieldCheck, Sparkles, Subtitles, ThumbsUp, Upload, Users, Video, X, BarChart3} from 'lucide-react'
import './styles.css'

const nav=[
  ['Dashboard',LayoutDashboard],['Content',Video],['Analytics',BarChart3],['Community',MessageSquare],['Subtitles',Subtitles],['Content detection',ShieldCheck]
]
const videos=[
  {title:'Ma première vidéo — présentation de la chaîne',type:'Vidéo',visibility:'Public',date:'Aujourd’hui',views:'1 248',likes:'96',comments:'18'},
  {title:'Studio Premium 2026 — aperçu',type:'Short',visibility:'Non répertorié',date:'Hier',views:'842',likes:'71',comments:'9'},
  {title:'Bienvenue sur ma chaîne',type:'Vidéo',visibility:'Privée',date:'12 sept. 2026',views:'0',likes:'0',comments:'0'}
]

function App(){
 const [page,setPage]=useState('Dashboard'); const [sidebar,setSidebar]=useState(true); const [search,setSearch]=useState(''); const [modal,setModal]=useState(null); const [toast,setToast]=useState(''); const [filter,setFilter]=useState('Tout');
 const notify=(m)=>{setToast(m);setTimeout(()=>setToast(''),2400)}
 const go=(p)=>{setPage(p);setSearch('')}
 const filtered=useMemo(()=>videos.filter(v=>filter==='Tout'||v.type===filter),[filter])
 return <div className="app">
  <header className="topbar"><button className="icon-btn" onClick={()=>setSidebar(!sidebar)}><Menu/></button><div className="brand"><span className="yt">▶</span><b>YouTube</b><span>Studio</span></div><div className="search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Rechercher dans Studio"/><kbd>⌘ K</kbd></div><div className="top-actions"><button className="ask" onClick={()=>notify('Ask Studio est prêt à recevoir votre question') }><Sparkles size={16}/> Ask Studio</button><button className="icon-btn" onClick={()=>notify('Aucune nouvelle notification')}><HelpCircle/></button><button className="icon-btn" onClick={()=>notify('Aucune nouvelle notification')}><Bell/></button><button className="create" onClick={()=>setModal('create')}><Plus size={18}/> Créer</button><div className="avatar">S</div></div></header>
  <div className="layout">
   <aside className={sidebar?'sidebar':'sidebar collapsed'}><div className="channel"><div className="channel-avatar">S</div><div><strong>Sofia CAROLLE</strong><span>@sofiacarolle</span></div></div>{nav.map(([n,I])=><button key={n} className={page===n?'nav active':'nav'} onClick={()=>go(n)}><I size={19}/><span>{n}</span></button>)}<div className="side-sep"/><button className="nav" onClick={()=>setModal('settings')}><Settings size={19}/><span>Paramètres</span></button><button className="nav" onClick={()=>notify('Merci pour votre retour !')}><MessageSquare size={19}/><span>Envoyer des commentaires</span></button></aside>
   <main className="main">{page==='Dashboard'&&<Dashboard go={go} setModal={setModal} notify={notify}/>} {page==='Content'&&<Content filtered={filtered} filter={filter} setFilter={setFilter} setModal={setModal} notify={notify}/>} {page==='Analytics'&&<Analytics/>} {page==='Community'&&<Community notify={notify}/>} {page==='Subtitles'&&<SubtitlesPage notify={notify}/>} {page==='Content detection'&&<Detection notify={notify}/>}</main>
  </div>
  {modal==='create'&&<CreateModal close={()=>setModal(null)} openUpload={()=>setModal('upload')} notify={notify}/>} {modal==='upload'&&<UploadModal close={()=>setModal(null)} notify={notify}/>} {modal==='settings'&&<SettingsModal close={()=>setModal(null)} notify={notify}/>} {toast&&<div className="toast">✓ {toast}</div>}
 </div>
}

function Header({title,subtitle,children}){return <div className="page-head"><div><h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{children}</div>}
function Card({children,className=''}){return <section className={'card '+className}>{children}</section>}
function Dashboard({go,setModal,notify}){return <><Header title="Tableau de bord" subtitle="Bienvenue dans votre espace de création."><button className="outline" onClick={()=>notify('Aide ouverte')}>Aide</button></Header><Card className="welcome"><div><span className="eyebrow">STUDIO PREMIUM</span><h2>Créez. Publiez. Faites grandir votre chaîne.</h2><p>Suivez vos performances, gérez vos contenus et développez votre audience depuis un seul espace.</p><div className="row"><button className="primary" onClick={()=>setModal('upload')}><Upload size={18}/> Importer une vidéo</button><button className="ghost" onClick={()=>go('Analytics')}>Voir les statistiques <ChevronRight size={17}/></button></div></div><div className="orb"><Clapperboard size={74}/></div></Card><div className="grid two"><Card><div className="card-title"><div><span className="muted">ANALYTIQUE DE LA CHAÎNE</span><h3>Vue d’ensemble</h3></div><button className="link" onClick={()=>go('Analytics')}>Voir plus</button></div><div className="metrics"><Metric label="Abonnés" value="12 480" change="+8,4 %"/><Metric label="Vues" value="284,6 k" change="+14,2 %"/><Metric label="Temps de visionnage" value="18,7 k h" change="+6,1 %"/></div><MiniChart/></Card><Card><div className="card-title"><div><span className="muted">ACTIVITÉ RÉCENTE</span><h3>Votre chaîne</h3></div><button className="icon-btn" onClick={()=>notify('Actualisé')}><Bell size={17}/></button></div><div className="activity"><Activity text="Nouvelle vidéo publiée" time="Il y a 2 h"/><Activity text="+120 nouveaux abonnés" time="Il y a 5 h"/><Activity text="Votre Short a dépassé 10 k vues" time="Hier"/></div></Card></div><div className="grid three"><Info title="Contenu" value="24 vidéos" icon={Video} onClick={()=>go('Content')}/><Info title="Communauté" value="18 commentaires" icon={Users} onClick={()=>go('Community')}/><Info title="Sous-titres" value="8 langues actives" icon={Subtitles} onClick={()=>go('Subtitles')}/></div></>}
function Metric({label,value,change}){return <div className="metric"><span>{label}</span><strong>{value}</strong><small>↗ {change}</small></div>}
function MiniChart(){return <svg className="chart" viewBox="0 0 600 150" preserveAspectRatio="none"><defs><linearGradient id="g" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#ff0033" stopOpacity=".35"/><stop offset="1" stopColor="#ff0033" stopOpacity="0"/></linearGradient></defs><path d="M0 125 C50 115 60 90 110 105 S170 75 220 90 S270 60 320 72 S380 40 430 58 S500 30 600 20 V150 H0Z" fill="url(#g)"/><path d="M0 125 C50 115 60 90 110 105 S170 75 220 90 S270 60 320 72 S380 40 430 58 S500 30 600 20" fill="none" stroke="#ff0033" strokeWidth="3"/></svg>}
function Activity({text,time}){return <div className="activity-row"><div className="dot"/><div><strong>{text}</strong><span>{time}</span></div></div>}
function Info({title,value,icon:I,onClick}){return <button className="info-card" onClick={onClick}><div className="info-icon"><I size={20}/></div><div><span>{title}</span><strong>{value}</strong></div><ChevronRight/></button>}
function Content({filtered,filter,setFilter,setModal,notify}){return <><Header title="Contenu" subtitle="Gérez vos vidéos, Shorts et diffusions en direct."><button className="primary" onClick={()=>setModal('upload')}><Upload size={18}/> Importer</button></Header><Card><div className="tabs"><button className={filter==='Tout'?'selected':''} onClick={()=>setFilter('Tout')}>Tout</button><button className={filter==='Vidéo'?'selected':''} onClick={()=>setFilter('Vidéo')}>Vidéos</button><button className={filter==='Short'?'selected':''} onClick={()=>setFilter('Short')}>Shorts</button><div className="spacer"/><button className="outline" onClick={()=>notify('Filtres avancés activés')}>Filtres</button></div><div className="table"><div className="tr th"><span>Contenu</span><span>Visibilité</span><span>Date</span><span>Vues</span><span>Interactions</span><span/></div>{filtered.map((v,i)=><div className="tr" key={i}><div className="video-cell"><div className="thumb">{v.type==='Short'?'S':'▶'}</div><div><strong>{v.title}</strong><small>{v.type}</small></div></div><span className="pill">{v.visibility}</span><span>{v.date}</span><span>{v.views}</span><span>{v.likes} j’aime · {v.comments} com.</span><button className="icon-btn" onClick={()=>notify('Options du contenu')}><MoreVertical/></button></div>)}</div></Card></>}
function Analytics(){return <><Header title="Analytics" subtitle="Comprenez vos performances et prenez de meilleures décisions."><button className="outline">Derniers 28 jours <ChevronDown size={16}/></button></Header><div className="grid three"><MetricCard t="Vues" v="284,6 k" c="+14,2 %"/><MetricCard t="Durée de visionnage" v="18,7 k h" c="+6,1 %"/><MetricCard t="Abonnés" v="+1 024" c="+8,4 %"/></div><Card className="analytics-card"><div className="card-title"><div><span className="muted">PERFORMANCES</span><h3>Vues au fil du temps</h3></div><div className="legend"><i/> Vues</div></div><MiniChart/><div className="axis"><span>1 sept.</span><span>8 sept.</span><span>15 sept.</span><span>22 sept.</span><span>28 sept.</span></div></Card></>}
function MetricCard({t,v,c}){return <Card><span className="muted">{t}</span><strong className="big-number">{v}</strong><small className="positive">↗ {c} sur la période</small></Card>}
function Community({notify}){return <><Header title="Communauté" subtitle="Interagissez avec votre audience."><button className="primary" onClick={()=>notify('Publication communautaire créée')}>Nouvelle publication</button></Header><div className="grid two"><Card><div className="card-title"><h3>Commentaires récents</h3><span className="count">18</span></div>{['Super vidéo, merci !','Le montage est incroyable 🔥','J’attends la prochaine avec impatience','Très clair et très utile'].map((x,i)=><div className="comment" key={i}><div className="mini-avatar">{String.fromCharCode(65+i)}</div><div><strong>Utilisateur {i+1}</strong><p>{x}</p><span>Il y a {i+2} h</span></div><button className="icon-btn" onClick={()=>notify('Commentaire marqué comme lu')}><ThumbsUp size={17}/></button></div>)}</Card><Card className="poll"><span className="eyebrow">SONDAGE</span><h3>Quel contenu voulez-vous voir ensuite ?</h3>{['Tutoriels','Coulisses','Shorts','Lives'].map((x,i)=><button key={x} onClick={()=>notify(`Vote enregistré : ${x}`)}><span>{x}</span><b>{[42,27,18,13][i]}%</b></button>)}</Card></div></>}
function SubtitlesPage({notify}){return <><Header title="Sous-titres" subtitle="Rendez vos contenus accessibles à davantage de spectateurs."><button className="primary" onClick={()=>notify('Nouvelle langue ajoutée')}>Ajouter une langue</button></Header><Card><div className="subtitle-grid">{['Français','English','Español','Deutsch','Português','Italiano'].map((x,i)=><div className="language" key={x}><div className="lang-icon"><Subtitles/></div><div><strong>{x}</strong><span>{i<3?'Publié':'Brouillon'}</span></div><ChevronRight/></div>)}</div></Card></>}
function Detection({notify}){return <><Header title="Détection de contenu" subtitle="Gérez les correspondances et les protections de vos contenus."><button className="outline" onClick={()=>notify('Paramètres de détection ouverts')}>Paramètres</button></Header><Card className="protection"><div className="shield"><ShieldCheck size={42}/></div><div><span className="eyebrow">PROTECTION ACTIVE</span><h2>Votre contenu est surveillé</h2><p>Les correspondances potentielles sont automatiquement signalées ici.</p></div></Card><div className="grid three"><MetricCard t="Correspondances" v="12" c="+3 cette semaine"/><MetricCard t="Résolues" v="9" c="75 % du total"/><MetricCard t="En attente" v="3" c="À examiner"/></div></>}
function CreateModal({close,openUpload,notify}){return <Modal close={close} title="Créer"><button className="modal-action" onClick={openUpload}><CloudUpload/><div><strong>Importer des vidéos</strong><span>Ajoutez un fichier depuis votre ordinateur</span></div><ChevronRight/></button><button className="modal-action" onClick={()=>notify('Éditeur de Short ouvert')}><Clapperboard/><div><strong>Créer un Short</strong><span>Transformez une idée en contenu vertical</span></div><ChevronRight/></button><button className="modal-action" onClick={()=>notify('Diffusion en direct préparée')}><PlaySquare/><div><strong>Passer en direct</strong><span>Lancez une diffusion pour votre audience</span></div><ChevronRight/></button></Modal>}
function UploadModal({close,notify}){const [file,setFile]=useState(null); return <Modal close={close} title="Importer une vidéo"><label className="drop"><input type="file" accept="video/*" onChange={e=>setFile(e.target.files?.[0]||null)}/><CloudUpload size={38}/><strong>{file?file.name:'Glissez-déposez votre vidéo ici'}</strong><span>ou cliquez pour parcourir · MP4, MOV, WebM</span></label><button className="primary full" disabled={!file} onClick={()=>{notify('Vidéo ajoutée au brouillon');close()}}>Continuer</button></Modal>}
function SettingsModal({close,notify}){return <Modal close={close} title="Paramètres"><div className="settings-row"><div><strong>Mode sombre</strong><span>Interface optimisée pour Studio</span></div><div className="toggle on" onClick={()=>notify('Préférence enregistrée')}><i/></div></div><div className="settings-row"><div><strong>Notifications</strong><span>Recevoir les alertes importantes</span></div><div className="toggle on" onClick={()=>notify('Préférence enregistrée')}><i/></div></div><button className="primary full" onClick={()=>{notify('Paramètres enregistrés');close()}}>Enregistrer</button></Modal>}
function Modal({close,title,children}){return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="modal-head"><h3>{title}</h3><button className="icon-btn" onClick={close}><X/></button></div>{children}</div></div>}

createRoot(document.getElementById('root')).render(<App/>)
